import React, { createContext, useContext, useState } from 'react';

/* ============================================================
   CropSense AI — i18n Translation System
   Languages: English, Hindi, Tamil, Telugu, Marathi,
              Kannada, Bengali, Gujarati
   ============================================================ */

export const LANGUAGES = [
  { code: 'en', label: 'English',  native: 'English',  flag: '🇬🇧' },
  { code: 'hi', label: 'Hindi',    native: 'हिंदी',     flag: '🇮🇳' },
  { code: 'ta', label: 'Tamil',    native: 'தமிழ்',    flag: '🌟' },
  { code: 'te', label: 'Telugu',   native: 'తెలుగు',   flag: '🌟' },
  { code: 'mr', label: 'Marathi',  native: 'मराठी',    flag: '🌟' },
  { code: 'kn', label: 'Kannada',  native: 'ಕನ್ನಡ',    flag: '🌟' },
  { code: 'bn', label: 'Bengali',  native: 'বাংলা',    flag: '🌟' },
  { code: 'gu', label: 'Gujarati', native: 'ગુજરાતી',  flag: '🌟' },
];

const T = {
  // ── Navbar ──────────────────────────────────────────────
  nav_home:      { en:'Home',     hi:'होम',      ta:'முகப்பு',   te:'హోమ్',    mr:'मुख्यपृष्ठ', kn:'ಹೋಮ್',   bn:'হোম',    gu:'હોમ'     },
  nav_detector:  { en:'Detector', hi:'डिटेक्टर', ta:'கண்டறி',   te:'డిటెక్టర్', mr:'डिटेक्टर', kn:'ಡಿಟೆಕ್ಟರ್', bn:'ডিটেক্টর', gu:'ડિટેક્ટર' },
  nav_advisory:  { en:'Advisory', hi:'सलाह',     ta:'ஆலோசனை',  te:'సలహా',    mr:'सल्ला',     kn:'ಸಲಹೆ',   bn:'পরামর্শ', gu:'સલાહ'    },
  nav_analyses:  { en:'Analyses', hi:'विश्लेषण',    ta:'பகுப்பாய்வு', te:'విశ్లేషణలు', mr:'विश्लेषणे', kn:'ವಿಶ್ಲೇಷಣೆ', bn:'বিশ্লেষণ', gu:'વિશ્લેષણ' },
  nav_chatbot:   { en:'AI Chat',  hi:'AI चैट',   ta:'AI அரட்டை', te:'AI చాట్', mr:'AI चॅट',   kn:'AI ಚಾಟ್', bn:'AI চ্যাট', gu:'AI ચેટ'  },
  nav_cta:       { en:'Scan Crop →', hi:'फसल स्कैन करें →', ta:'பயிர் ஸ்கேன் →', te:'పంట స్కాన్ →', mr:'पीक स्कॅन →', kn:'ಬೆಳೆ ಸ್ಕ್ಯಾನ್ →', bn:'ফসল স্ক্যান →', gu:'પાક સ્કેન →' },

  // ── Landing Page ─────────────────────────────────────────
  hero_pill:     { en:'AI Model Online · Free to Use', hi:'AI मॉडल ऑनलाइन · मुफ़्त', ta:'AI மாடல் ஆன்லைன் · இலவசம்', te:'AI మోడల్ ఆన్‌లైన్ · ఉచితం', mr:'AI मॉडेल ऑनलाइन · मोफत', kn:'AI ಮಾಡೆಲ್ ಆನ್‌ಲೈನ್ · ಉಚಿತ', bn:'AI মডেল অনলাইন · বিনামূল্যে', gu:'AI મોડેલ ઓનલાઈન · મફત' },
  hero_line1:    { en:'Detect Crop', hi:'फसल रोग',    ta:'பயிர் நோய்',   te:'పంట వ్యాధి',   mr:'पीक रोग',    kn:'ಬೆಳೆ ರೋಗ',   bn:'ফসলের রোগ',  gu:'પાક રોગ'    },
  hero_line2:    { en:'Diseases',    hi:'पहचानें',    ta:'கண்டறிதல்',    te:'గుర్తించండి',  mr:'ओळखा',       kn:'ಪತ್ತೆ',      bn:'শনাক্ত করুন', gu:'શોધો'       },
  hero_line3:    { en:'Instantly',   hi:'तुरंत',      ta:'உடனடியாக',     te:'వెంటనే',       mr:'त्वरित',     kn:'ತಕ್ಷಣ',      bn:'তাৎক্ষণিক',  gu:'તરત જ'      },
  hero_sub:      { en:'Point your camera at any affected leaf. Get instant AI diagnosis, treatment plans, and nearby dealer locations in under 3 seconds.', hi:'किसी भी प्रभावित पत्ती पर कैमरा लगाएं। 3 सेकंड में AI डायग्नोसिस, उपचार योजना पाएं।', ta:'பாதிக்கப்பட்ட இலையை கேமரா பிடியுங்கள். 3 வினாடியில் AI நோய் கண்டறிதல்.', te:'ప్రభావిత ఆకుపై కెమెరా పెట్టండి. 3 సెకన్లలో AI రోగ నిర్ధారణ పొందండి.', mr:'प्रभावित पानावर कॅमेरा लावा. 3 सेकंदात AI निदान मिळवा.', kn:'ಪ್ರಭಾವಿತ ಎಲೆಯ ಮೇಲೆ ಕ್ಯಾಮೆರಾ ಹಿಡಿಯಿರಿ. 3 ಸೆಕೆಂಡ್‌ಗಳಲ್ಲಿ AI ರೋಗ ಗುರುತಿಸುವಿಕೆ.', bn:'যেকোনো আক্রান্ত পাতায় ক্যামেরা ধরুন। ৩ সেকেন্ডে AI রোগ নির্ণয় পান।', gu:'અસરગ્રસ્ત પાન પર કેમેરા ધરો. 3 સેકન્ડમાં AI નિદાન મળે.' },
  hero_btn1:     { en:'Start Free Scan', hi:'मुफ़्त स्कैन शुरू करें', ta:'இலவச ஸ்கேன் தொடங்கு', te:'ఉచిత స్కాన్ ప్రారంభించు', mr:'मोफत स्कॅन सुरू', kn:'ಉಚಿತ ಸ್ಕ್ಯಾನ್ ಪ್ರಾರಂಭ', bn:'বিনামূল্যে স্ক্যান', gu:'મફત સ્કેન શરૂ' },
  hero_btn2:     { en:'Farm Advisory', hi:'कृषि सलाह', ta:'விவசாய ஆலோசனை', te:'వ్యవసాయ సలహా', mr:'शेती सल्ला', kn:'ಕೃಷಿ ಸಲಹೆ', bn:'কৃষি পরামর্শ', gu:'ખેતી સલાહ' },
    // Landing page — stats, features, steps
    stats_crop_loss:    { en: 'Crop loss prevented' },
    stats_avg_scan:     { en: 'Average scan time' },
    stats_diseases:     { en: 'Diseases detected' },
    stats_languages:    { en: 'Languages supported' },
    label_accuracy:     { en: 'Accuracy' },
    detection_rate:     { en: 'Detection rate' },
    label_speed:        { en: 'Speed' },
    per_diagnosis:      { en: 'Per diagnosis' },
    label_database:     { en: 'Database' },
    diseases_listed:    { en: 'Diseases listed' },
    label_languages:    { en: 'Languages' },
    regional_langs:     { en: 'Regional langs' },
    platform_eyebrow:   { en: 'Platform' },
    feats_title_part1:  { en: 'A Complete' },
    feats_title_fill:   { en: 'AgriTech' },
    feats_title_part2:  { en: 'Platform' },
    feats_body:         { en: 'Built from the ground up for Indian farmers. No expertise needed — just point, shoot, and get answers in your language.' },
    feat_treatment_title:{ en: 'Smart Treatment' },
    feat_treatment_body: { en: 'Chemical & organic remedy plans tailored to your crop and disease severity.' },
    feat_calendar_title: { en: 'Crop Calendar' },
    feat_calendar_body:  { en: 'Month-by-month farming guide with weather insights and planting tips.' },
    feat_chat_title:     { en: 'AI Farming Chat' },
    feat_chat_body:      { en: 'Ask any farming question in your language. Powered by Claude AI — instant expert answers.' },
    feat_schemes_title:  { en: 'Govt Schemes' },
    feat_schemes_body:   { en: 'PM-KISAN, PMFBY, Soil Health Cards — all key subsidies in one place.' },
    process_eyebrow:    { en: 'Process' },
    hiw_title_part1:     { en: '4 Steps to' },
    hiw_title_fill:      { en: 'Save' },
    hiw_title_part2:     { en: 'Your Crop' },
    step_photo_title:    { en: 'Take a Photo' },
    step_photo_body:     { en: 'Snap the affected leaf clearly in natural daylight.' },
    step_ai_title:       { en: 'AI Analyzes' },
    step_ai_body:        { en: 'Our model scans 50+ diseases in under 3 seconds.' },
    step_results_title:  { en: 'Get Results' },
    step_results_body:   { en: 'Disease name, severity score, and full treatment.' },
    step_action_title:   { en: 'Take Action' },
    step_action_body:    { en: 'Find nearby dealers and apply the remedy today.' },
    feat_hero_title:     { en: 'Instant AI Disease Detection' },
    feat_hero_body:      { en: 'Trained on 100,000+ crop images. Detects 50+ diseases with 94% accuracy. Chemical & organic treatment plans included for every diagnosis.' },
    feat_hero_cta:       { en: 'Try it now' },
    bubble_treatment_ready:{ en: '✓ Treatment Ready' },
    bubble_diseases:     { en: '🌿 50+ Diseases' },
    bubble_free:         { en: '★ Free Forever' },
    cta_start_scan:      { en: 'Start Crop Scan — Free' },
    cta_explore_advisory: { en: 'Explore Advisory' },
    footer_copy:         { en: 'Built for farmers, by innovators.' },
    hero_result_label:   { en: '⚠ Disease Detected' },
    hero_result_name:    { en: 'Late Blight' },
    label_severity_short:{ en: 'Severity' },
    det_choose_photo:    { en: 'Choose Photo' },
    det_upload_hint:     { en: 'Drag & drop your crop image here, or click to browse your device gallery' },
    drop_it_here:        { en: 'Drop it here!' },
    analyzing:          { en: 'Analyzing…' },
    det_photo_tips:      { en: 'Photo Tips' },
    det_detectable_title:{ en: 'Detectable Diseases' },
      // detector step labels
      det_step_upload:            { en: 'Uploading image...' },
      det_step_detect_species:    { en: 'Detecting plant species...' },
      det_step_scanning_pathogens:{ en: 'Scanning for pathogens...' },
      det_step_generating_plan:   { en: 'Generating treatment plan...' },
      det_step_complete:          { en: 'Analysis complete!' },
      // detector tips
      det_tip_focus:              { en: 'Ensure the leaf is in sharp focus with no blur' },
      det_tip_natural_light:      { en: 'Photograph in natural daylight for best accuracy' },
      det_tip_show_area:          { en: 'Show the entire affected area of the leaf' },
      det_tip_no_shadows:         { en: 'Avoid shadows or glare covering the disease spots' },
      // static status & toasts
      det_model_status:           { en: 'AI Model: Online · 94% Accuracy' },
      det_error_image_too_large:  { en: 'Image too large. Max 10MB.' },
      det_error_please_upload:    { en: 'Please upload a crop image first!' },
      det_toast_image_loaded:     { en: 'Image loaded!' },
      det_toast_analysis_failed:  { en: 'Analysis failed.' },
      // disease names
      disease_late_blight:        { en: 'Late Blight' },
      disease_leaf_rust:          { en: 'Leaf Rust' },
      disease_powdery_mildew:     { en: 'Powdery Mildew' },
      disease_bacterial_wilt:     { en: 'Bacterial Wilt' },
      disease_leaf_spot:          { en: 'Leaf Spot' },
      disease_mosaic_virus:       { en: 'Mosaic Virus' },
      disease_root_rot:           { en: 'Root Rot' },
      disease_downy_mildew:       { en: 'Downy Mildew' },
      disease_anthracnose:        { en: 'Anthracnose' },
      disease_fusarium_wilt:      { en: 'Fusarium Wilt' },
      disease_grey_mold:          { en: 'Grey Mold' },
      disease_scab:               { en: 'Scab' },
      disease_alternaria:         { en: 'Alternaria' },
      disease_smut:               { en: 'Smut' },
    // Result page
    res_healthy_title:   { en: 'Your Crop is Healthy! 🎉' },
    res_healthy_body:    { en: 'No diseases detected. Your plant appears to be in excellent condition.' },
    res_maintenance_tips:{ en: 'Maintenance Tips' },
    res_tip_water:       { en: 'Water at base only, early morning preferred.' },
    res_tip_monitor:     { en: 'Monitor weekly for early signs of pests.' },
    res_tip_spacing:     { en: 'Maintain proper spacing for airflow.' },
    res_tip_micronutrients: { en: 'Apply micronutrients for continued health.' },
    // Additional ResultPage keys
    res_healthy_msg:     { en: 'No issues detected — keep up the good care!' },
    res_other_possibilities:{ en: 'Other possible diagnoses' },
    seasonal_risk:       { en: 'Seasonal Risk' },
    tab_about:           { en: 'About' },
    tab_treatment:       { en: 'Treatment' },
    tab_dealers:         { en: 'Dealers' },
    // Chat page
    chat_assistant_label:   { en: 'AI Assistant' },
    chat_suggested:         { en: 'Suggested Questions' },
    chat_topics:            { en: 'Topics' },
    chat_quick_stats:       { en: 'Quick Stats' },
    chat_start_conversation:{ en: 'Start a Conversation' },
    chat_input_hint:        { en: 'Press Enter to send · Shift+Enter for new line' },

    // Chat topics (used in sidebar quick topic chips)
    chat_topic_late_blight:      { en: 'Late Blight' },
    chat_topic_pm_kisan:         { en: 'PM-KISAN' },
    chat_topic_drip_irrigation:  { en: 'Drip Irrigation' },
    chat_topic_organic_farming:  { en: 'Organic Farming' },
    chat_topic_rabi_season:      { en: 'Rabi Season' },
    chat_topic_wheat_disease:    { en: 'Wheat Disease' },
    chat_topic_paddy_pest:       { en: 'Paddy Pest' },
    chat_topic_soil_testing:     { en: 'Soil Testing' },
    chat_topic_crop_insurance:   { en: 'Crop Insurance' },
    chat_topic_neem_oil:         { en: 'Neem Oil' },
    chat_topic_vermicompost:     { en: 'Vermicompost' },
    chat_topic_intercropping:    { en: 'Intercropping' },

    // Sidebar stats labels
    stat_diseases_covered: { en: 'Diseases covered' },
    stat_treatment_guides: { en: 'Treatment guides' },
    stat_govt_schemes:     { en: 'Govt schemes listed' },
    stat_crop_varieties:   { en: 'Crop varieties' },

  // ── Detector Page ────────────────────────────────────────
  det_eyebrow:   { en:'Disease Scanner', hi:'रोग स्कैनर', ta:'நோய் ஸ்கேனர்', te:'వ్యాధి స్కానర్', mr:'रोग स्कॅनर', kn:'ರೋಗ ಸ್ಕ್ಯಾನರ್', bn:'রোগ স্ক্যানার', gu:'રોગ સ્કેનર' },
  det_title1:    { en:'Crop Disease', hi:'फसल रोग', ta:'பயிர் நோய்', te:'పంట వ్యాధి', mr:'पीक रोग', kn:'ಬೆಳೆ ರೋಗ', bn:'ফসল রোগ', gu:'પાક રોગ' },
  det_title2:    { en:'Detector',     hi:'डिटेक्टर', ta:'கண்டறிவி',   te:'డిటెక్టర్',  mr:'डिटेक्टर', kn:'ಡಿಟೆಕ್ಟರ್', bn:'ডিটেক্টর', gu:'ડિટેક્ટર' },
  det_sub:       { en:'Upload a clear photo of your affected crop leaf for instant AI diagnosis', hi:'तत्काल AI निदान के लिए प्रभावित पत्ती की स्पष्ट फोटो अपलोड करें', ta:'உடனடி AI நோய் கண்டறிதலுக்கு பாதிக்கப்பட்ட இலையின் தெளிவான புகைப்படம்', te:'తక్షణ AI నిర్ధారణ కోసం ప్రభావిత ఆకు యొక్క స్పష్టమైన ఫోటో అప్‌లోడ్ చేయండి', mr:'तात्काळ AI निदानासाठी प्रभावित पानाचा स्पष्ट फोटो अपलोड करा', kn:'ತಕ್ಷಣ AI ರೋಗ ಗುರುತಿಸಲು ಪ್ರಭಾವಿತ ಎಲೆಯ ಸ್ಪಷ್ಟ ಫೋಟೋ', bn:'তাৎক্ষণিক AI নির্ণয়ের জন্য আক্রান্ত পাতার স্পষ্ট ছবি আপলোড করুন', gu:'તાત્કાલિક AI નિદાન માટે અસરગ્રસ્ત પાનનો સ્પષ્ટ ફોટો અપલોડ કરો' },
  det_analyze:   { en:'Detect Disease Now', hi:'अभी रोग पहचानें', ta:'இப்போது நோய் கண்டறி', te:'ఇప్పుడు వ్యాధి కనుగొనండి', mr:'आता रोग ओळखा', kn:'ಈಗ ರೋಗ ಪತ್ತೆ ಮಾಡಿ', bn:'এখনই রোগ শনাক্ত করুন', gu:'હવે રોગ શોધો' },
  det_upload_title: { en:'Upload Leaf Photo', hi:'पत्ती की फोटो अपलोड करें', ta:'இலை புகைப்படம் பதிவேற்று', te:'ఆకు ఫోటో అప్‌లోడ్ చేయండి', mr:'पानाचा फोटो अपलोड करा', kn:'ಎಲೆ ಫೋಟೋ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ', bn:'পাতার ছবি আপলোড করুন', gu:'પાનનો ફોટો અપલોડ કરો' },

  // ── Advisory Page ────────────────────────────────────────
  adv_title1:    { en:'Smart',      hi:'स्मार्ट',    ta:'ஸ்மார்ட்',   te:'స్మార్ట్',   mr:'स्मार्ट',   kn:'ಸ್ಮಾರ್ಟ್',   bn:'স্মার্ট',   gu:'સ્માર્ટ'  },
  adv_title2:    { en:'Farming',    hi:'खेती',       ta:'விவசாயம்',   te:'వ్యవసాయం',  mr:'शेती',      kn:'ಕೃಷಿ',       bn:'কৃষি',      gu:'ખેતી'     },
  adv_title3:    { en:'Guide',      hi:'गाइड',       ta:'வழிகாட்டி',  te:'గైడ్',      mr:'मार्गदर्शक', kn:'ಮಾರ್ಗದರ್ಶಿ', bn:'গাইড',      gu:'ગાઇડ'     },
  adv_sub:       { en:'Seasonal insights, expert tips, and a live crop calendar — everything for a great harvest.', hi:'मौसमी जानकारी, विशेषज्ञ सुझाव और लाइव फसल कैलेंडर।', ta:'பருவகால தகவல்கள், நிபுணர் குறிப்புகள் மற்றும் நேரடி பயிர் நாட்காட்டி.', te:'సీజనల్ అంతర్దృష్టులు, నిపుణుల చిట్కాలు మరియు లైవ్ పంట క్యాలెండర్.', mr:'हंगामी माहिती, तज्ञ टिप्स आणि थेट पीक कॅलेंडर.', kn:'ಋತುಮಾನ ಒಳನೋಟಗಳು, ತಜ್ಞ ಸಲಹೆಗಳು ಮತ್ತು ನೇರ ಬೆಳೆ ಕ್ಯಾಲೆಂಡರ್.', bn:'মৌসুমী তথ্য, বিশেষজ্ঞ টিপস এবং লাইভ ফসল ক্যালেন্ডার।', gu:'મોસમી આંતરદૃષ્ટિ, નિષ્ણાત ટિપ્સ અને લાઈવ પાક કેલેન્ડર.' },
  adv_today:     { en:"Today's Advisory", hi:'आज की सलाह', ta:'இன்றைய ஆலோசனை', te:'నేటి సలహా', mr:'आजचा सल्ला', kn:'ಇಂದಿನ ಸಲಹೆ', bn:'আজকের পরামর্শ', gu:'આજની સલાહ' },
  adv_wx_good:   { en:'Good conditions for spraying. Low wind speed ensures minimal drift. Carry out pending foliar applications today.', hi:'छिड़काव के लिए अच्छी परिस्थितियाँ। कम हवा गति सुनिश्चित करती है न्यूनतम बहाव।', ta:'தெளித்தல் நல்ல நிலைமைகள். குறைந்த காற்று வேகம் குறைந்த ஓட்டத்தை உறுதி செய்கிறது.', te:'పిచికారీకి మంచి పరిస్థితులు. తక్కువ గాలి వేగం కనిష్ట ప్రవాహాన్ని నిర్ధారిస్తుంది.', mr:'फवारणीसाठी चांगल्या परिस्थिती. कमी वारा वेग किमान वाहून जाणे सुनिश्चित करतो.', kn:'ಸಿಂಪಡಿಸಲು ಉತ್ತಮ ಪರಿಸ್ಥಿತಿಗಳು. ಕಡಿಮೆ ಗಾಳಿ ವೇಗ ಕನಿಷ್ಠ ಹರಿಯುವಿಕೆ ಖಚಿತಪಡಿಸುತ್ತದೆ.', bn:'স্প্রে করার জন্য ভালো অবস্থা। কম বায়ু গতি ন্যূনতম প্রবাহ নিশ্চিত করে।', gu:'છંટકાવ માટે સારી સ્થિતિ. ઓછી પવન ગતિ ન્યૂનતમ ડ્રિફ્ટ સુનિશ્ચિત કરે છે.' },
  adv_schemes:   { en:'Government Schemes for Farmers', hi:'किसानों के लिए सरकारी योजनाएं', ta:'விவசாயிகளுக்கான அரசு திட்டங்கள்', te:'రైతులకు ప్రభుత్వ పథకాలు', mr:'शेतकऱ्यांसाठी सरकारी योजना', kn:'ರೈತರಿಗೆ ಸರ್ಕಾರಿ ಯೋಜನೆಗಳು', bn:'কৃষকদের জন্য সরকারি প্রকল্প', gu:'ખેડૂતો માટે સરકારી યોજનાઓ' },
  adv_helpline:  { en:'Kisan Call Center', hi:'किसान कॉल सेंटर', ta:'கிசான் கால் சென்டர்', te:'కిసాన్ కాల్ సెంటర్', mr:'किसान कॉल सेंटर', kn:'ಕಿಸಾನ್ ಕಾಲ್ ಸೆಂಟರ್', bn:'কিসান কল সেন্টার', gu:'કિસાન કૉલ સેન્ટર' },
  adv_toll:      { en:'Toll Free · 24 / 7', hi:'टोल फ्री · 24/7', ta:'கட்டணமில்லா · 24/7', te:'టోల్ ఫ్రీ · 24/7', mr:'टोल फ्री · 24/7', kn:'ಉಚಿತ · 24/7', bn:'বিনামূল্যে · ২৪/৭', gu:'ટોલ ફ્રી · 24/7' },

  // ── Chat Page ────────────────────────────────────────────
  chat_title:    { en:'AI Farming', hi:'AI कृषि',    ta:'AI விவசாயம்', te:'AI వ్యవసాయం', mr:'AI शेती',  kn:'AI ಕೃಷಿ',   bn:'AI কৃষি',   gu:'AI ખેતી'  },
  chat_title2:   { en:'Assistant',  hi:'सहायक',      ta:'உதவியாளர்',  te:'సహాయకుడు',  mr:'सहाय्यक',  kn:'ಸಹಾಯಕ',    bn:'সহকারী',   gu:'સહાયક'    },
  chat_sub:      { en:'Ask me anything about crops, diseases, weather, government schemes, or farming practices.', hi:'फसलों, रोगों, मौसम, सरकारी योजनाओं के बारे में कुछ भी पूछें।', ta:'பயிர்கள், நோய்கள், வானிலை, அரசு திட்டங்கள் பற்றி எதையும் கேளுங்கள்.', te:'పంటలు, వ్యాధులు, వాతావరణం, ప్రభుత్వ పథకాల గురించి ఏదైనా అడగండి.', mr:'पिके, रोग, हवामान, सरकारी योजनांबद्दल काहीही विचारा.', kn:'ಬೆಳೆಗಳು, ರೋಗಗಳು, ಹವಾಮಾನ, ಸರ್ಕಾರಿ ಯೋಜನೆಗಳ ಬಗ್ಗೆ ಏನಾದರೂ ಕೇಳಿ.', bn:'ফসল, রোগ, আবহাওয়া, সরকারি প্রকল্প সম্পর্কে যেকোনো কিছু জিজ্ঞাসা করুন।', gu:'પાક, રોગ, હવામાન, સરકારી યોજનાઓ વિશે ગમે તે પૂછો.' },
  chat_placeholder: { en:'Ask about crop diseases, treatments, irrigation, soil...', hi:'फसल रोग, उपचार, सिंचाई के बारे में पूछें...', ta:'பயிர் நோய்கள், சிகிச்சைகள் பற்றி கேளுங்கள்...', te:'పంట వ్యాధులు, చికిత్సల గురించి అడగండి...', mr:'पीक रोग, उपचारांबद्दल विचारा...', kn:'ಬೆಳೆ ರೋಗಗಳು, ಚಿಕಿತ್ಸೆಗಳ ಬಗ್ಗೆ ಕೇಳಿ...', bn:'ফসলের রোগ, চিকিৎসা সম্পর্কে জিজ্ঞাসা করুন...', gu:'પાક રોગ, સારવાર વિશે પૂછો...' },
  chat_send:     { en:'Send',      hi:'भेजें',     ta:'அனுப்பு',    te:'పంపండి',   mr:'पाठवा',    kn:'ಕಳುಹಿಸಿ',  bn:'পাঠান',    gu:'મોકલો'    },
  chat_thinking: { en:'Thinking…', hi:'सोच रहा हूं…', ta:'யோசிக்கிறேன்…', te:'ఆలోచిస్తున్నాను…', mr:'विचार करतोय…', kn:'ಯೋಚಿಸುತ್ತಿದ್ದೇನೆ…', bn:'ভাবছি…', gu:'વિચારી રહ્યો છું…' },
  chat_welcome:  { en:'Namaste! 🙏 I\'m your AI farming assistant. I can help you with crop disease identification, treatment plans, fertilizer advice, irrigation tips, government schemes, and more. What\'s troubling your crops today?', hi:'नमस्ते! 🙏 मैं आपका AI कृषि सहायक हूं। फसल रोग, उपचार, खाद सलाह, सिंचाई, सरकारी योजनाओं में मदद कर सकता हूं।', ta:'நமஸ்தே! 🙏 நான் உங்கள் AI விவசாய உதவியாளர். பயிர் நோய், சிகிச்சை, உரம், நீர்ப்பாசனம் பற்றி உதவுவேன்.', te:'నమస్తే! 🙏 నేను మీ AI వ్యవసాయ సహాయకుడిని. పంట వ్యాధులు, చికిత్స, ఎరువులు, సాగునీటి సలహాలు ఇవ్వగలను.', mr:'नमस्कार! 🙏 मी तुमचा AI शेती सहाय्यक आहे. पीक रोग, उपचार, खत, सिंचन, सरकारी योजनांबद्दल मदत करू शकतो.', kn:'ನಮಸ್ಕಾರ! 🙏 ನಾನು ನಿಮ್ಮ AI ಕೃಷಿ ಸಹಾಯಕ. ಬೆಳೆ ರೋಗ, ಚಿಕಿತ್ಸೆ, ಗೊಬ್ಬರ, ನೀರಾವರಿ ಸಲಹೆ ನೀಡಬಲ್ಲೆ.', bn:'নমস্তে! 🙏 আমি আপনার AI কৃষি সহকারী। ফসল রোগ, চিকিৎসা, সার, সেচ, সরকারি প্রকল্প সম্পর্কে সাহায্য করতে পারি।', gu:'નમસ્તે! 🙏 હું તમારો AI ખેતી સહાયક છું. પાક રોગ, સારવાર, ખાતર, સિંચાઈ, સરકારી યોજનાઓ વિશે મદદ કરી શકું છું.' },

  // ── Result Page ──────────────────────────────────────────
  res_back:      { en:'Back to Scanner', hi:'स्कैनर पर वापस', ta:'ஸ்கேனருக்கு திரும்பு', te:'స్కానర్‌కు తిరిగి', mr:'स्कॅनरकडे परत', kn:'ಸ್ಕ್ಯಾನರ್‌ಗೆ ಹಿಂತಿರುಗಿ', bn:'স্ক্যানারে ফিরুন', gu:'સ્કેનર પર પાછા' },
  res_complete:  { en:'Analysis Complete', hi:'विश्लेषण पूर्ण', ta:'பகுப்பாய்வு முடிந்தது', te:'విశ్లేషణ పూర్తయింది', mr:'विश्लेषण पूर्ण', kn:'ವಿಶ್ಲೇಷಣೆ ಪೂರ್ಣ', bn:'বিশ্লেষণ সম্পন্ন', gu:'વિશ્લેષણ સંપૂર્ণ' },
  res_scan_new:  { en:'Scan New Crop', hi:'नई फसल स्कैन', ta:'புதிய பயிர் ஸ்கேன்', te:'కొత్త పంట స్కాన్', mr:'नवीन पीक स्कॅन', kn:'ಹೊಸ ಬೆಳೆ ಸ್ಕ್ಯಾನ್', bn:'নতুন ফসল স্ক্যান', gu:'નવો પાક સ્કેન' },

  // ── Analyses Page ───────────────────────────────────────
  analyses_title:     { en: 'Analysis History' },
  loading_analyses:   { en: 'Loading analyses...' },
  no_analyses:        { en: 'No analyses saved yet. Upload a crop image to get started!' },
  unknown_analysis:   { en: 'Unknown Analysis' },
  label_disease:      { en: 'Disease' },
  healthy:            { en: '✓ Healthy' },
  label_confidence:   { en: 'Confidence' },
  click_view_details: { en: 'Click to view details →' },
  label_severity:     { en: 'Severity' },
  high_risk:          { en: 'High Risk' },
  medium_risk:        { en: 'Medium Risk' },
  low_risk:           { en: 'Low Risk' },
  label_detected:     { en: 'Detected' },
  disease_overview:   { en: 'Disease Overview' },
  disease_description:{ en: 'is a plant disease that affects crop health and productivity. Prompt identification and management are crucial to prevent crop losses.' },
  detected_on:        { en: 'Detected on' },
  immediate_action:   { en: 'Immediate action is recommended to prevent spread.' },

  // ── Weather widget ───────────────────────────────────────
  wx_humidity:   { en:'Humidity', hi:'आर्द्रता', ta:'ஈரப்பதம்', te:'తేమ', mr:'आर्द्रता', kn:'ಆರ್ದ್ರತೆ', bn:'আর্দ্রতা', gu:'ભેજ' },
  wx_wind:       { en:'Wind',     hi:'हवा',      ta:'காற்று',   te:'గాలి',  mr:'वारा',    kn:'ಗಾಳಿ',    bn:'বায়ু',    gu:'પવન' },
  wx_uv:         { en:'UV Index', hi:'UV इंडेक्स', ta:'UV குறியீடு', te:'UV సూచిక', mr:'UV निर्देशांक', kn:'UV ಸೂಚ್ಯಂಕ', bn:'UV সূচক', gu:'UV ઇન્ડેક્સ' },
  wx_feels:      { en:'Feels Like', hi:'महसूस होता है', ta:'உணர்கிறது', te:'అనిపిస్తుంది', mr:'जाणवते', kn:'ಅನಿಸುತ್ತದೆ', bn:'অনুভব হয়', gu:'લાગે છે' },

  // ── Common ───────────────────────────────────────────────
  common_free:   { en:'Free to Use', hi:'मुफ़्त', ta:'இலவசம்', te:'ఉచితం', mr:'मोफत', kn:'ಉಚಿತ', bn:'বিনামূল্যে', gu:'મફત' },
  common_try:    { en:'Try it now', hi:'अभी आज़माएं', ta:'இப்போது முயற்சி', te:'ఇప్పుడు ప్రయత్నించండి', mr:'आत्ता वापरा', kn:'ಈಗ ಪ್ರಯತ್ನಿಸಿ', bn:'এখনই চেষ্টা করুন', gu:'હવે અજમાવો' },
  auto_window_scrollto_0_0_pathname_return_null_function_app_return: { en: "{\n    window.scrollTo(0, 0);\n  }, [pathname]);\n  return null;\n}\n\nfunction App() {\n  return (" },
  auto_main_routes: { en: "{/* Main Routes */}" },
  auto_placeholder_routes_for_footer_links_to_resolve_eslint_warnin: { en: "{/* Placeholder routes for Footer links to resolve ESLint warnings */}" },
  auto_privacy_policy_coming_soon: { en: "Privacy Policy coming soon." },
  auto_api_documentation_coming_soon: { en: "API Documentation coming soon." },
  auto_contact_support_coming_soon: { en: "Contact Support coming soon." },
  auto_404_catch_all: { en: "{/* 404 Catch-all */}" },
  auto_render: { en: "{\n  render(" },
  auto_document_removeeventlistener_mousedown_fn_return: { en: "document.removeEventListener('mousedown', fn);\r\n  }, []);\r\n\r\n  return (" },
  auto_open: { en: "{open && (" },
  auto_lang_l_code: { en: "{lang === l.code &&" },
  auto_setopen_false_loc_const_links_to_key_nav_home_to_detect_key_: { en: "setOpen(false), [loc]);\r\n\r\n  const links = [\r\n    { to: '/',         key: 'nav_home'     },\r\n    { to: '/detect',   key: 'nav_detector' },\r\n    { to: '/advisory', key: 'nav_advisory' },\r\n    { to: '/analyses', key: 'nav_analyses' },\r\n    { to: '/chat',     key: 'nav_chatbot'  },\r\n  ];\r\n\r\n  return (" },
  auto_cropsense: { en: "CropSense" },
  auto_t_l_key: { en: "{t(l.key)}" },
  auto_open_1: { en: "{open ?" },
  auto_t_key_t_key_lang_t_key_t_key_en_key_return: { en: "(T[key] && T[key][lang]) || (T[key] && T[key]['en']) || key;\r\n  return (" },
  auto_children: { en: "{children}" },
  auto_title_smart_irrigation_color_00ff87_tips_water_early_morning: { en: ", title:'Smart Irrigation', color:'#00ff87', tips:['Water early morning (5–8 AM) to cut evaporation','Use drip irrigation to save 40–60% water','Check soil moisture before each irrigation cycle','Avoid waterlogging — it causes severe root disease'] },\r\n  { icon:" },
  auto_title_soil_health_color_b8ff3c_tips_test_soil_ph_every_2_yea: { en: ", title:'Soil Health', color:'#b8ff3c', tips:['Test soil pH every 2 years (ideal: 6.0–7.0)','Add farmyard manure (FYM) before every planting','Practice crop rotation to break disease cycles','Use green manure crops like dhaincha in summer'] },\r\n  { icon:" },
  auto_title_pest_management_color_ffe03a_tips_monitor_crops_twice_: { en: ", title:'Pest Management', color:'#ffe03a', tips:['Monitor crops twice a week during critical growth','Use pheromone traps for early pest detection','Follow IPM — biological control comes first','Spray pesticides at dawn or dusk only'] },\r\n  { icon:" },
  auto_loadweather_city_city_return: { en: "{ loadWeather(city); }, [city]);\r\n\r\n  return (" },
  auto_header: { en: "{/* Header */}" },
  auto_farm_advisory: { en: "Farm Advisory" },
  auto_t_adv_title1: { en: "{t('adv_title1')}" },
  auto_weather_card_live: { en: "{/* Weather card — LIVE */}" },
  auto_weather_isreal: { en: "{weather?.isReal\r\n                ?" },
  auto_live: { en: "Live" },
  auto_demo: { en: "Demo" },
  auto_wxloading: { en: "{wxLoading ? (" },
  auto_fetching_weather: { en: "Fetching weather…" },
  auto_weather: { en: ") : weather && (" },
  auto_icon: { en: "{[\r\n                    {icon:" },
  auto_val_weather_humidity_lbl_t_wx_humidity_icon: { en: ", val:`${weather.humidity}%`,       lbl:t('wx_humidity')},\r\n                    {icon:" },
  auto_val_weather_windspeed_km_h_lbl_t_wx_wind_icon: { en: ", val:`${weather.windSpeed} km/h`,  lbl:t('wx_wind')    },\r\n                    {icon:" },
  auto_val_uv_weather_uvindex_lbl_t_wx_uv_icon: { en: ", val:`UV ${weather.uvIndex??'—'}`, lbl:t('wx_uv')      },\r\n                    {icon:" },
  auto_0: { en: "0 && (" },
  auto_0_1: { en: "0 &&" },
  auto_f_rain: { en: "💧{f.rain}%" },
  auto_calendar: { en: "{/* Calendar */}" },
  auto_crop_calendar: { en: "Crop Calendar" },
  auto_2024_india: { en: "2024 · India" },
  auto_kharif_season: { en: "🌾 Kharif Season" },
  auto_rabi_season: { en: "🌿 Rabi Season" },
  auto_action_required: { en: "⚡ Action Required" },
  auto_tips: { en: "{/* Tips */}" },
  auto_expert_farming_tips: { en: "Expert Farming Tips" },
  auto_schemes: { en: "{/* Schemes */}" },
  auto_t_adv_schemes: { en: "🏛️ {t('adv_schemes')}" },
  auto_helpline: { en: "{/* Helpline */}" },
  auto_free_24_7_agricultural_helpline_for_all_farmers_across_india: { en: "Free 24/7 agricultural helpline for all farmers across India" },
  auto_1800_180_1551: { en: "1800-180-1551" },
  auto_item_id_id_console_log_analysis_deleted_successfully_else_al: { en: "item._id !== id));\r\n        console.log('Analysis deleted successfully');\r\n      } else {\r\n        alert('Failed to delete: ' + (data.error || 'Unknown error'));\r\n      }\r\n    } catch (err) {\r\n      console.error('Delete error:', err);\r\n      alert('Error deleting analysis: ' + err.message);\r\n    }\r\n  };\r\n\r\n  return (" },
  auto_t_analyses_title: { en: "🔍 {t('analyses_title')}" },
  auto_loading: { en: "{loading ? (" },
  auto_error: { en: ") : error ? (" },
  auto_t_error_error: { en: "⚠️ {t('error')}: {error}" },
  auto_items_length_0: { en: "{items.length === 0 ? (" },
  auto_t_no_analyses: { en: "📭 {t('no_analyses')}" },
  auto_it_summary_it_disease_t_unknown_analysis: { en: "📋 {it.summary || (it.disease || t('unknown_analysis'))}" },
  auto_t_label_disease: { en: "🦠 {t('label_disease')}" },
  auto_t_label_confidence: { en: "📊 {t('label_confidence')}" },
  auto_t_click_view_details: { en: "{t('click_view_details')}" },
  auto_detail_modal_selectedanalysis: { en: "{/* Detail Modal */}\r\n      {selectedAnalysis && (" },
  auto_selectedanalysis_disease_disease_details: { en: "{selectedAnalysis.disease ? (\r\n              // Disease Details" },
  auto_math_round_selectedanalysis_confidence_100: { en: "{Math.round(selectedAnalysis.confidence * 100)}%" },
  auto_tabs: { en: "{/* Tabs */}" },
  auto_about: { en: "ℹ️ About" },
  auto_treatment: { en: "💊 Treatment" },
  auto_dealers: { en: "🏪 Dealers" },
  auto_about_tab_activetab_about: { en: "{/* About Tab */}\r\n                {activeTab === 'about' && (" },
  auto_0_4_t_medium_risk_t_low_risk: { en: "0.4 ? t('medium_risk') : t('low_risk')}" },
  auto_treatment_tab_activetab_treatment: { en: ")}\r\n\r\n                {/* Treatment Tab */}\r\n                {activeTab === 'treatment' && (" },
  auto_chemical_treatment: { en: "💉 Chemical Treatment" },
  auto_consult_local_agronomist_for_best_fungicide_recommendations: { en: "Consult local agronomist for best fungicide recommendations" },
  auto_apply_chemical_treatments_in_early_morning_or_late_evening: { en: "Apply chemical treatments in early morning or late evening" },
  auto_follow_label_instructions_carefully_for_dosage_and_safety: { en: "Follow label instructions carefully for dosage and safety" },
  auto_repeat_applications_every_7_10_days_as_recommended: { en: "Repeat applications every 7-10 days as recommended" },
  auto_wear_protective_equipment_during_application: { en: "Wear protective equipment during application" },
  auto_organic_treatment: { en: "🌿 Organic Treatment" },
  auto_spray_neem_oil_solution_5ml_litre_every_5_7_days: { en: "Spray neem oil solution (5ml/litre) every 5-7 days" },
  auto_use_sulfur_dust_or_powder_for_preventive_care: { en: "Use sulfur dust or powder for preventive care" },
  auto_apply_baking_soda_solution_1_tsp_per_litre_water: { en: "Apply baking soda solution (1 tsp per litre water)" },
  auto_improve_air_circulation_by_pruning_affected_areas: { en: "Improve air circulation by pruning affected areas" },
  auto_remove_and_destroy_infected_plant_parts: { en: "Remove and destroy infected plant parts" },
  auto_general_management_tips: { en: "General Management Tips" },
  auto_remove_heavily_infected_leaves_and_dispose_properly: { en: "Remove heavily infected leaves and dispose properly" },
  auto_avoid_overhead_irrigation_water_at_the_base_only: { en: "Avoid overhead irrigation - water at the base only" },
  auto_ensure_proper_plant_spacing_for_air_circulation: { en: "Ensure proper plant spacing for air circulation" },
  auto_monitor_crops_regularly_for_early_detection: { en: "Monitor crops regularly for early detection" },
  auto_practice_crop_rotation_to_reduce_disease_pressure: { en: "Practice crop rotation to reduce disease pressure" },
  auto_dealers_tab_activetab_dealers: { en: ")}\r\n\r\n                {/* Dealers Tab */}\r\n                {activeTab === 'dealers' && (" },
  auto_agro_care_store: { en: "Agro Care Store" },
  auto_1_2_km: { en: "1.2 km" },
  auto_fungicides_seeds_fertilizers: { en: "Fungicides, Seeds, Fertilizers" },
  auto_kisan_s_corner: { en: "Kisan's Corner" },
  auto_2_8_km: { en: "2.8 km" },
  auto_organic_natural_remedies: { en: "Organic & Natural Remedies" },
  auto_farmmart_india: { en: "FarmMart India" },
  auto_4_1_km: { en: "4.1 km" },
  auto_all_agrochemicals: { en: "All Agrochemicals" },
  auto_green_valley_seeds: { en: "Green Valley Seeds" },
  auto_5_3_km: { en: "5.3 km" },
  auto_certified_seeds_pesticides: { en: "Certified Seeds & Pesticides" },
  auto_dealers_shown_are_based_on_your_location_for_specific_recomm: { en: "📍 Dealers shown are based on your location. For specific recommendations about treatments and products for" },
  auto_consult_with_store_staff: { en: ", consult with store staff." },
  auto_healthy_plant_details: { en: ") : (\r\n              // Healthy Plant Details" },
  auto_plant_is_healthy: { en: "✓ Plant is Healthy" },
  auto_your_plant_appears_to_be_in_good_health_continue_monitoring_: { en: "Your plant appears to be in good health! Continue monitoring and maintain proper care routines." },
  auto_analyzed: { en: "ANALYZED" },
  auto_delete_this_analysis: { en: "Delete this analysis" },
  auto_else_if_line_startswith_line_endswith_elements_push: { en: ");\r\n    } else if (line.startsWith('**') && line.endsWith('**')) {\r\n      elements.push(" },
  auto_else_if_line_startswith_line_startswith_const_items_while_i: { en: ");\r\n    } else if (line.startsWith('- ') || line.startsWith('• ')) {\r\n      const items = [];\r\n      while (i" },
  auto_i_elements_push: { en: ");\r\n        i++;\r\n      }\r\n      elements.push(" },
  auto_continue_else_if_line_trim_const_parts_line_split_g_elements: { en: ");\r\n      continue;\r\n    } else if (line.trim()) {\r\n      const parts = line.split(/(\\*\\*[^*]+\\*\\*|`[^`]+`)/g);\r\n      elements.push(" },
  auto_if_p_startswith_p_endswith_return: { en: "{\r\n            if (p.startsWith('**') && p.endsWith('**')) return" },
  auto_if_p_startswith_p_endswith_return_1: { en: ";\r\n            if (p.startsWith('`')  && p.endsWith('`'))  return" },
  auto_return_p: { en: ";\r\n            return p;\r\n          })}" },
  auto_i_return: { en: ");\r\n    }\r\n    i++;\r\n  }\r\n  return" },
  auto_t_k_return: { en: "t(k));\r\n\r\n  return (" },
  auto_t_chat_title: { en: "{t('chat_title')}" },
  auto_t_common_free_powered_by_claude_ai: { en: "{t('common_free')} · Powered by Claude AI" },
  auto_s_q: { en: "{s.q}" },
  auto_topic: { en: "{topic}" },
  auto_msgs_length_0: { en: "{msgs.length === 0 ? (" },
  auto_loading_1: { en: "))\r\n            )}\r\n\r\n            {loading && (" },
  auto_settimeout_r_350_sessionstorage_setitem_cropresult_json_stri: { en: "setTimeout(r, 350));\r\n\r\n      sessionStorage.setItem('cropResult', JSON.stringify({...res, imageUrl: img}));\r\n      nav('/result');\r\n    } catch(e) {\r\n      toast.error(e.message || t('det_toast_analysis_failed'));\r\n      setRunning(false);\r\n      setStep(0);\r\n    }\r\n  };\r\n\r\n  return (" },
  auto_t_det_model_status: { en: "{t('det_model_status')}" },
  auto_grid: { en: "{/* Grid */}" },
  auto_left: { en: "{/* Left */}" },
  auto_img: { en: "{!img ? (" },
  auto_t_det_choose_photo: { en: "{t('det_choose_photo')}" },
  auto_running: { en: "{!running && (" },
  auto_running_1: { en: "{running && (" },
  auto_running_2: { en: "{running ?" },
  auto_t_analyzing: { en: "{t('analyzing')}" },
  auto_t_det_analyze: { en: "{t('det_analyze')}" },
  auto_i_step: { en: ":\r\n                       i===step ?" },
  auto_right: { en: "{/* Right */}" },
  auto_t_det_photo_tips: { en: "{t('det_photo_tips')}" },
  auto_tip: { en: "{tip}" },
  auto_t_det_detectable_title: { en: "{t('det_detectable_title')}" },
  auto_crop: { en: "Crop" },
  auto_titlekey_feat_treatment_title_bodykey_feat_treatment_body_c_: { en: ", titleKey:'feat_treatment_title', bodyKey:'feat_treatment_body', c:'#b8ff3c' },\r\n  { icon:" },
  auto_titlekey_feat_calendar_title_bodykey_feat_calendar_body_c_ff: { en: ", titleKey:'feat_calendar_title', bodyKey:'feat_calendar_body', c:'#ffb23f' },\r\n  { icon:" },
  auto_titlekey_feat_chat_title_bodykey_feat_chat_body_c_a78bfa_ico: { en: ", titleKey:'feat_chat_title', bodyKey:'feat_chat_body', c:'#a78bfa' },\r\n  { icon:" },
  auto_titlekey_feat_schemes_title_bodykey_feat_schemes_body_c_ff3d: { en: ", titleKey:'feat_schemes_title', bodyKey:'feat_schemes_body', c:'#ff3d3d' },\r\n];\r\n\r\nconst STEPS = [\r\n  { emoji:'📸', titleKey:'step_photo_title', bodyKey:'step_photo_body', n:'01' },\r\n  { emoji:'🤖', titleKey:'step_ai_title', bodyKey:'step_ai_body', n:'02' },\r\n  { emoji:'📋', titleKey:'step_results_title', bodyKey:'step_results_body', n:'03' },\r\n  { emoji:'✅', titleKey:'step_action_title', bodyKey:'step_action_body', n:'04' },\r\n];\r\n\r\nconst CROPS = [\r\n  {l:'Wheat',c:'#f5e642'},{l:'Rice Paddy',c:'#00ff87'},{l:'Sugarcane',c:'#ffb23f'},\r\n  {l:'Tomato',c:'#ff5757'},{l:'Cotton',c:'#ffffff'},{l:'Soybean',c:'#b8ff3c'},\r\n  {l:'Maize',c:'#f5e642'},{l:'Potato',c:'#ffb23f'},{l:'Chili',c:'#ff5757'},\r\n  {l:'Onion',c:'#c084fc'},{l:'Mango',c:'#ffb23f'},{l:'Banana',c:'#f5e642'},\r\n];\r\n\r\nexport default function LandingPage() {\r\n  const { t } = useLang();\r\n  const dbl = [...TICKER,...TICKER];\r\n  const dblC1 = [...CROPS,...CROPS];\r\n  const dblC2 = [...CROPS.slice(6),...CROPS.slice(0,6),...CROPS.slice(6),...CROPS.slice(0,6)];\r\n\r\n  return (" },
  auto_hero: { en: "{/* ── HERO ── */}" },
  auto_t_hero_pill: { en: "{t('hero_pill')}" },
  auto_t_hero_btn1: { en: "{t('hero_btn1')}" },
  auto_t_hero_btn2: { en: "{t('hero_btn2')}" },
  auto_mockup: { en: "{/* Mockup */}" },
  auto_t_label_accuracy: { en: "{t('label_accuracy')}" },
  auto_94: { en: "94%" },
  auto_t_label_speed: { en: "{t('label_speed')}" },
  auto_2_8s: { en: "2.8s" },
  auto_phone: { en: "{/* Phone */}" },
  auto_67: { en: "67%" },
  auto_t_label_database: { en: "{t('label_database')}" },
  auto_50: { en: "50+" },
  auto_t_label_languages: { en: "{t('label_languages')}" },
  auto_ticker: { en: "{/* ── TICKER ── */}" },
  auto_d: { en: "{d}" },
  auto_stats: { en: "{/* ── STATS ── */}" },
  auto_features: { en: "{/* ── FEATURES ── */}" },
  auto_t_feats_title_part1: { en: "{t('feats_title_part1')}" },
  auto_t_feat_hero_cta: { en: "{t('feat_hero_cta')}" },
  auto_how_it_works: { en: "{/* ── HOW IT WORKS ── */}" },
  auto_t_hiw_title_part2: { en: "{t('hiw_title_part2')}" },
  auto_crop_marquee: { en: "{/* ── CROP MARQUEE ── */}" },
  auto_c_l: { en: "{c.l}" },
  auto_cta: { en: "{/* ── CTA ── */}" },
  auto_get_started: { en: "Get Started" },
  auto_protect_your_harvest: { en: "Protect Your Harvest." },
  auto_start_for_free_today: { en: "Start For Free Today." },
  auto_join_farmers_across_india_using_ai_to_detect_diseases_early_: { en: "Join farmers across India using AI to detect diseases early and save their crops." },
  auto_t_cta_start_scan: { en: "{t('cta_start_scan')}" },
  auto_t_cta_explore_advisory: { en: "{t('cta_explore_advisory')}" },
  auto_footer: { en: "{/* ── FOOTER ── */}" },
  auto_2024_cropsense_ai_t_footer_copy: { en: "© 2024 CropSense AI · {t('footer_copy')}" },
  auto_privacy: { en: "Privacy" },
  auto_api: { en: "API" },
  auto_contact: { en: "Contact" },
  auto_const_s_sessionstorage_getitem_cropresult_if_s_nav_detect_re: { en: "{\r\n    const s = sessionStorage.getItem('cropResult');\r\n    if (!s) { nav('/detect'); return; }\r\n    try {\r\n      setRes(JSON.parse(s));\r\n    } catch (e) {\r\n      nav('/detect');\r\n    }\r\n  }, [nav]);\r\n\r\n  if (!res) return null;\r\n\r\n  // ─── FIX: isHealthy must be read from the TOP LEVEL of the result object.\r\n  // Your old code: `const { isHealthy } = res` — works only if plantApi returns it at top level.\r\n  // plantApi now always returns isHealthy at top level, but this fallback keeps it safe.\r\n  const isHealthy   = res.isHealthy ?? res.plantInfo?.isHealthy ?? false;\r\n  const { disease, imageUrl, isDemo, allDetected } = res;\r\n\r\n  // Guard: if not healthy but disease data is missing, go back\r\n  if (!isHealthy && !disease) { nav('/detect'); return null; }\r\n\r\n  if (isHealthy) {\r\n  return (" },
  auto_t_res_back: { en: "{t('res_back')}" },
  auto_t_res_maintenance_tips: { en: "{t('res_maintenance_tips')}" },
  auto_t_res_scan_new: { en: "{t('res_scan_new')}" },
  auto_isdemo: { en: "{isDemo && (" },
  auto_demo_mode: { en: "Demo Mode" },
  auto_showing_sample_results_add_plant_id_api_key_for_real_detecti: { en: "— Showing sample results. Add Plant.id API key for real detection." },
  auto_header_1: { en: ")}\r\n\r\n        {/* Header */}" },
  auto_detected_with: { en: "Detected with" },
  auto_0_affects_disease_affectedcrops_join: { en: "0 && ` · Affects: ${disease.affectedCrops.join(', ')}`}" },
  auto_confidence_math_round_disease_probability_100: { en: "Confidence: {Math.round(disease.probability*100)}%" },
  auto_1: { en: "1 && (" },
  auto_40_var_caution_var_plasma_return: { en: "40?'var(--caution)':'var(--plasma)';\r\n                  return (" },
  auto_k_about_l_about_i: { en: "{[\r\n                  {k:'about',   l:'About',     i:" },
  auto_t_i_t_l: { en: "{t.i} {t.l}" },
  auto_tab_about: { en: "{tab==='about' && (" },
  auto_affects: { en: "Affects" },
  auto_seasonal_risk: { en: "Seasonal Risk" },
  auto_severity: { en: "Severity" },
  auto_confidence: { en: "Confidence" },
  auto_tab_treat: { en: ")}\r\n                {tab==='treat' && (" },
  auto_chemical: { en: "⚗️ Chemical" },
  auto_organic: { en: "🌿 Organic" },
  auto_tab_dealers: { en: ")}\r\n                {tab==='dealers' && (" },
  auto_scan_new_crop: { en: "Scan New Crop" },
  auto_crop_1: { en: "crop" },
  auto_20_return_text_high_winds_today_spraying_not_recommended_che: { en: "20) return { text: 'High winds today. Spraying not recommended — chemical drift risk is high. Wait for calmer conditions.', icon: '💨', alert: '💨 Too windy to spray' };\r\n  if (wind" },
  auto_38_return_text_extreme_heat_today_water_crops_at_dawn_and_du: { en: "38) return { text: 'Extreme heat today. Water crops at dawn and dusk only. Avoid any chemical applications — leaf burn risk.', icon: '🔥', alert: '🌡️ Extreme heat — water crops' };\r\n  if (temp" },
  auto_200_code: { en: "= 200 && code" },
  auto_300_code: { en: "= 300 && code" },
  auto_500_code: { en: "= 500 && code" },
  auto_600_code: { en: "= 600 && code" },
  auto_700_code: { en: "= 700 && code" },
  auto_settimeout_r_600_return_getmockweather_city_try_const_geo_aw: { en: "setTimeout(r, 600));\r\n    return getMockWeather(city);\r\n  }\r\n\r\n  try {\r\n    const geo = await fetch(\r\n      `https://api.openweathermap.org/geo/1.0/direct?q=${encodeURIComponent(city)}&limit=1&appid=${OW_KEY}`\r\n    );\r\n    const geoData = await geo.json();\r\n    if (!geoData.length) throw new Error('City not found');\r\n    const { lat, lon, name, country } = geoData[0];\r\n\r\n    const res = await fetch(\r\n      `https://api.openweathermap.org/data/2.5/weather?lat=${lat}&lon=${lon}&appid=${OW_KEY}&units=metric`\r\n    );\r\n    const data = await res.json();\r\n    if (!res.ok) throw new Error(data.message || 'Weather fetch failed');\r\n\r\n    const forecast = await fetch(\r\n      `https://api.openweathermap.org/data/2.5/forecast?lat=${lat}&lon=${lon}&appid=${OW_KEY}&units=metric&cnt=8`\r\n    );\r\n    const fData = await forecast.json();\r\n\r\n    const advisory = getFarmingAdvisory(data);\r\n    const isNight  = data.dt" },

};

const LangContext = createContext();

export function LangProvider({ children }) {
  const [lang, setLang] = useState('en');

  const t = (key) => {
    if (!key) return '';
    if (T[key] && T[key][lang]) return T[key][lang];
    if (T[key] && T[key]['en']) return T[key]['en'];
    return key;
  };

  return (
    <LangContext.Provider value={{ lang, setLang, t, LANGUAGES }}>
      {children}
    </LangContext.Provider>
  );
}

export function useLang() { return useContext(LangContext); }
export default LangContext;